#!/bin/bash

# Move stills into an archive directory.
# Calling format from pikrellcam or a at-commands script:
#    archive-still [day|still.jpg] yyyy-mm-dd $a $m $P $G
#
# Which pikrellcam expands into:
#    archive-still day       yyyy-mm-dd archive-dir media-dir FIFO LOG
# or
#    archive-still still.jpg yyyy-mm-dd archive-dir media-dir FIFO LOG

# If $1 is the string "day", move all stills for the day yyyy-mm-dd into
#   the archive directory archive-dir/yyyy/mm/dd/stills
# Otherwise, $1 should be a jpg still and it
#   is moved into the archive directory.


DAY_FLAG=$1
STILL=$1
DATE=$2
ARCHIVE_DIR=$3
MEDIA_DIR=$4
FIFO=$5
LOG_FILE=$6


LEN=${#DATE}

if [[ "$LEN" -ne "10" ]]
then
	echo "  archive-still bad date string: $DATE" >> $LOG_FILE
	exit 1
fi

# From DATE arg: yyyy-mm-dd, DATE_PATH is: yyyy/mm/dd
YEAR=`expr substr $DATE 1 4`
MONTH=`expr substr $DATE 6 2`
DAY=`expr substr $DATE 9 2`

DATE_PATH=$YEAR/$MONTH/$DAY

ARCHIVE_STILLS_PATH=$ARCHIVE_DIR/$DATE_PATH/stills

YEAR=`expr substr $DATE 1 4`
MONTH=`expr substr $DATE 6 2`
DAY=`expr substr $DATE 9 2`

create_dir()
	{
	DIR=$1
	if [ ! -d $DIR ]
	then
		mkdir $DIR
		sudo chown :www-data $DIR
		sudo chmod 775  $DIR
	fi
	}

create_dir $ARCHIVE_DIR/$YEAR
create_dir $ARCHIVE_DIR/$YEAR/$MONTH
create_dir $ARCHIVE_DIR/$YEAR/$MONTH/$DAY
create_dir $ARCHIVE_STILLS_PATH

if [ "$DAY_FLAG" == "day" ]
then
	echo "  archive-still day $DATE to $ARCHIVE_DIR/$DATE_PATH" >> $LOG_FILE
	mv $MEDIA_DIR/stills/*${DATE}*.jpg $ARCHIVE_STILLS_PATH
else
	echo "  archive-still $STILL to $ARCHIVE_DIR/$DATE_PATH" >> $LOG_FILE
	mv $MEDIA_DIR/stills/$STILL $ARCHIVE_STILLS_PATH
fi

# Cleanup in case no files were moved so archive page won't show dangling links
#
find $ARCHIVE_STILLS_PATH -maxdepth 0 -empty -exec rmdir $ARCHIVE_STILLS_PATH \;

ARCHIVE_DATE_PATH=$ARCHIVE_DIR/$DATE_PATH
find $ARCHIVE_DATE_PATH -maxdepth 0 -empty -exec rmdir $ARCHIVE_DATE_PATH \;
