#!/bin/bash

# This is a motion event on_motion_preview_save script.
# Uncomment lines to enable emailing the preview jpeg, copying the preview
# jpeg, or taking a still
#
# uncomment any echo lines to the LOG_FILE if you want logging.
#
# Argument substitution done by PiKrellCam before running this script:
#   $C - scripts directory so this script is found.
#   $F - the preview jpeg filename full path (from MJPEG_DIR)
#   $m - the media directory full path
#   $P - the command FIFO
#   $G - log file configured in ~/.pikrellcam/pikrellcam.conf.
#   $A - the filename full path of the thumb jpeg of the motion area
#        Note: if motion_preview_save_mode is "first" and the detect
#        that triggers this script is audio or external, then there is no
#        motion area and the thumb jpeg will be from the full preview jpeg.
#        Additionally, if there is subsequent motion, the thumb jpeg will
#        be renamed after the motion video ends.
#
# In ~/.pikrellcam.conf, for this script as is, make on_motion_preview_save:
#
# on_motion_preview_save  $C/preview-save  $F $m $P $G

PREVIEW_JPEG=$1
MEDIA_DIR=$2
FIFO=$3
LOG_FILE=$4
THUMB_JPEG=$5

# To configure emailing a jpeg for a motion event, uncomment one EMAIL_JPG
# line, edit the MY_EMAIL line, and uncomment the mpack line:

# If you want to email the full mjpeg_width preview jpg, uncomment this line:
# EMAIL_JPEG=$PREVIEW_JPEG
# OR, to email the smaller motion area thumb jpg, uncomment this line:
# EMAIL_JPEG=$THUMB_JPEG

# Edit MY_EMAIL to your email address to email the preview jpeg and uncomment
# the mpack line.  Run mpack in the background because if it is slow in
# sending the email, pikrellcam is waiting for this script to end and the
# preview display can pause.
#
MY_EMAIL=myuser@gmail.com
#mpack -s pikrellcam@$HOSTNAME $EMAIL_JPEG $MY_EMAIL &

#echo "mpack -s pikrellcam@$HOSTNAME $PREVIEW_JPEG $MY_EMAIL &" >> $LOG_FILE



# uncomment to copy the low resolution preview jpeg to the stills directory.
# Edit PREVIEW_JPEG_DIR to copy it anywhere you want.
#
PREVIEW_JPEG_DIR=$MEDIA_DIR/stills
#cp $PREVIEW_JPEG $PREVIEW_JPEG_DIR
#echo "cp $PREVIEW_JPEG $PREVIEW_JPEG_DIR" >> $LOG_FILE



# NOTE: taking a full resolution still can put a glitch into the motion
# video being recorded because the camera has to switch modes, however,
# uncomment if you do want to take a still.  This is probably only useful if
# preview_save_mode is "first" because if the mode is "best" the still will
# be taken after the action has ended.  So use the on_motion_begin command
# to take a still if preview_save_mode is "best".  The on_motion_begin
# command can be a script like this or the internal command "@still"
#
#echo "still" > $FIFO
#echo "preview save script: still" >> $LOG_FILE
