#!/bin/bash

# Script to run commands on timelapse files when a timelapse is ended.
# This script should be configured in ~/.pikrellcam/pikrellcam.conf and not
#   in the at-command.conf file.  Eg in pikrellcam.conf:
#   on_timelapse_end $C/timelapse-end $L $T $n $G $l
#
# Argument substitution done by PiKrellCam before running this script:
#   $C - scripts directory so this script is found.
#   $L - the timelapse directory full path
#   $T - the timelapse video filename full path output name.  The path puts the
#        video in the video directory.
#   $n - the timelapse series just ended printed as %05d.
#   $G - log file configured in ~/.pikrellcam/pikrellcam.conf.
#   $P - the command FIFO full path.
#   $l - the timelapse temporary file name format suitable for use with avconv.
#        PiKrellCam uses a temporary file name format of tl_$n_$N.jpg.  So if
#        for example the just ended timelapse series is 22, the timelapse temp
#        files in the timelapse subdir will be: tl_00022_xxxxx.jpg where xxxxx
#        will be the sequence numbers for the timelapse snapshots.
#        In this case the $l variable will be:  tl_00022_%05d.jpg.
#        WARNING: Since a '%' is embeded in the string, the $l must be the
#        last variable given in the on_timelapse_end string.
#

TIMELAPSE_DIR=$1
VIDEOFILE_MP4=$2
SERIES=$3
LOG_FILE=$4
COMMAND_FIFO=$5
FILENAME_FORMAT=$6

#
# Requires libav-tools
#

DATE=`date +"%F %T"`
echo "  $DATE Timelapse-end: converting $FILENAME_FORMAT to $VIDEOFILE_MP4" >> $LOG_FILE

echo "tl_inform_convert $SERIES.mp4" > $COMMAND_FIFO

cd $TIMELAPSE_DIR
nice -2 avconv -r 6 -i $FILENAME_FORMAT \
		-b:v 6M -maxrate 6M -minrate 1M -bufsize 4M \
		-r 6 -vcodec libx264 -crf 20 -g 4 \
		$SERIES.mp4

mv $SERIES.mp4 $VIDEOFILE_MP4
echo "tl_inform_convert done" > $COMMAND_FIFO


rm tl_${SERIES}_*.jpg

DATE=`date +"%F %T"`
echo "  $DATE Timelapse-end: $VIDEOFILE_MP4 done" >> $LOG_FILE
